CREATE TABLE `registro_nomina` (
	`id` int AUTO_INCREMENT NOT NULL,
	`sucursalId` int NOT NULL,
	`empleadoId` int NOT NULL,
	`fecha` varchar(10) NOT NULL,
	`turnoEsperado` varchar(4),
	`horaEntradaEsperada` varchar(5),
	`horaSalidaEsperada` varchar(5),
	`timestampEntrada` bigint,
	`timestampSalida` bigint,
	`aperturaId` int,
	`cierreId` int,
	`horasTrabajadas` float,
	`minutosRetardo` int DEFAULT 0,
	`estado` enum('presente','retardo','ausente','ausencia_justificada','descanso','sin_horario') NOT NULL DEFAULT 'sin_horario',
	`editadoManualmente` boolean NOT NULL DEFAULT false,
	`editadoPorId` int,
	`justificacion` text,
	`tipoJustificacion` enum('enfermedad','permiso_personal','emergencia_familiar','capacitacion','vacaciones','error_sistema','otro'),
	`fotoJustificacionUrl` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `registro_nomina_id` PRIMARY KEY(`id`)
);
