import mysql from "mysql2/promise";
import dotenv from "dotenv";
dotenv.config();

// Puntos actualizados: duplicados eliminados, solapados fusionados, 18 nuevas preguntas agregadas
const PUNTOS = [
  // ─── 1. Puntos Generales ─────────────────────────────────────────────────
  { codigo: "PG1", seccionNumero: 1, seccionNombre: "Puntos Generales", categoria: "Higiene", descripcion: "El establecimiento está limpio y sin evidencia visual de plaga o insectos", criterio: "No cumple si existe alguna evidencia de plaga, tales como cucarachas o ratones, así como sus desechos.", valor: 5, orden: 1 },
  { codigo: "PG2", seccionNumero: 1, seccionNombre: "Puntos Generales", categoria: "Imagen", descripcion: "La primera impresión en el establecimiento es de orden y una atmósfera agradable", criterio: "Los equipos, accesorios y sabores están ordenados. El área de auto servicio bien rellenada y limpia. La música es agradable en género y volumen.", valor: 5, orden: 2 },
  { codigo: "PG3", seccionNumero: 1, seccionNombre: "Puntos Generales", categoria: "Control", descripcion: "En todas las ventas se registra en el sistema POS y se entrega el ticket al cliente", criterio: "Sin excepción, se registra en el sistema todas las ventas y se entrega el ticket al cliente que ordena. El sistema debe estar activo en todo momento.", valor: 5, orden: 3 },
  { codigo: "PG4", seccionNumero: 1, seccionNombre: "Puntos Generales", categoria: "Hospitalidad", descripcion: "El personal fue amable, sonriente y sugiere algún sabor en especial", criterio: "Siempre, los M.E. están sonrientes, con actitud de servicio, promoviendo una venta sugestiva y ofreciendo degustación al inicio o en la entrega del Snowtea.", valor: 5, orden: 4 },
  { codigo: "PG5", seccionNumero: 1, seccionNombre: "Puntos Generales", categoria: "Mantenimiento", descripcion: "Todos los equipos operativos están funcionando correctamente", criterio: "A simple vista, todos los equipos operando: Droper, selladora, licuadoras, Redwash y computadora. Los focos y luminarias se evalúan en la sección de Instalaciones.", valor: 5, orden: 5 },
  { codigo: "PG6", seccionNumero: 1, seccionNombre: "Puntos Generales", categoria: "Operación", descripcion: "Se encuentran correctamente surtidas todas las materias primas", criterio: "Cuentan con el 100% de las materias primas que son necesarias para la preparación de las bebidas, que están ofertadas en el menú.", valor: 5, orden: 6 },
  { codigo: "PG7", seccionNumero: 1, seccionNombre: "Puntos Generales", categoria: "Control", descripcion: "Se tiene el número de teléfono de emergencia del franquiciante visible en el local", criterio: "Número de contacto de soporte Snowtea visible para el personal en caso de emergencia operativa. Puede estar en la BUOS o en un lugar visible del área de trabajo.", valor: 3, orden: 7 },
  { codigo: "PG8", seccionNumero: 1, seccionNombre: "Puntos Generales", categoria: "Hospitalidad", descripcion: "El tiempo de espera del cliente desde el pedido hasta la entrega es menor a 3 minutos", criterio: "Medido durante la visita de evaluación. Aplica para pedidos estándar sin personalización excesiva. Si hay fila, se mide desde que el cliente es atendido.", valor: 5, orden: 8 },
  // ─── 2. Entrada al Local ──────────────────────────────────────────────────
  { codigo: "EL1", seccionNumero: 2, seccionNombre: "Entrada al Local o Llegada a la Isla", categoria: "Mantenimiento", descripcion: "La fachada se encuentra en buenas condiciones y sin cuarteaduras", criterio: "Visualmente el local se observa en buen estado, limpio, sin calcomanías, sin grafiti. La pintura debe estar en el tono original y sin deslave.", valor: 3, orden: 1 },
  { codigo: "EL2", seccionNumero: 2, seccionNombre: "Entrada al Local o Llegada a la Isla", categoria: "Imagen", descripcion: "Cuenta con los colores permitidos por Snowtea", criterio: "La fachada debe estar previamente revisada y autorizada por Snowtea, y cualquier cambio debe ser avisado previamente.", valor: 3, orden: 2 },
  { codigo: "EL3", seccionNumero: 2, seccionNombre: "Entrada al Local o Llegada a la Isla", categoria: "Imagen", descripcion: "El logotipo del anuncio de la fachada es claro", criterio: "Se encuentra completo, y en el caso de ser luminoso prende en todas sus partes.", valor: 3, orden: 3 },
  { codigo: "EL4", seccionNumero: 2, seccionNombre: "Entrada al Local o Llegada a la Isla", categoria: "Imagen", descripcion: "Únicamente se encuentra el logotipo institucional en la fachada", criterio: "Solo se puede tener el logotipo Snowtea autorizado. No puede haber ninguna otra marca.", valor: 3, orden: 4 },
  { codigo: "EL5", seccionNumero: 2, seccionNombre: "Entrada al Local o Llegada a la Isla", categoria: "Operación", descripcion: "Cumple con los horarios establecidos de apertura y cierre", criterio: "Tiene que ser visible al cliente y siempre respetar los horarios.", valor: 5, orden: 5 },
  { codigo: "EL6", seccionNumero: 2, seccionNombre: "Entrada al Local o Llegada a la Isla", categoria: "Higiene", descripcion: "La terraza se encuentra limpia", criterio: "Barrida al menos 2 veces al día, libre de chicles en el piso. En el caso de tener sombrillas, estas deben ser lavadas con profundidad, al menos 1 vez a la semana.", valor: 5, orden: 6 },
  { codigo: "EL7", seccionNumero: 2, seccionNombre: "Entrada al Local o Llegada a la Isla", categoria: "Higiene", descripcion: "Las mesas de la terraza se encuentran limpias", criterio: "Sin polvo y que no estén percudidas.", valor: 5, orden: 7 },
  { codigo: "EL8", seccionNumero: 2, seccionNombre: "Entrada al Local o Llegada a la Isla", categoria: "Higiene", descripcion: "Los sillones o sillas de la terraza están limpias y en buenas condiciones", criterio: "Sin polvo y que no estén percudidas. Al menos se tienen que lavar profundo una vez a la semana.", valor: 5, orden: 8 },
  { codigo: "EL9", seccionNumero: 2, seccionNombre: "Entrada al Local o Llegada a la Isla", categoria: "Higiene", descripcion: "El piso de la entrada se encuentra limpio y sin manchas", criterio: "Diariamente se tiene que empezar el turno con el piso limpio y trapeado. Sin manchas visibles ni residuos.", valor: 5, orden: 9 },
  { codigo: "EL10", seccionNumero: 2, seccionNombre: "Entrada al Local o Llegada a la Isla", categoria: "Higiene", descripcion: "Los cristales y acrílicos se encuentran sin manchas y limpios", criterio: "Se encuentran sin dedos o manchas marcadas y al momento de ser limpiados, se utiliza un trapo específico para no mezclar olores ni sabores.", valor: 5, orden: 10 },
  { codigo: "EL11", seccionNumero: 2, seccionNombre: "Entrada al Local o Llegada a la Isla", categoria: "Higiene", descripcion: "Los botes de basura están limpios y sin excedente de basura", criterio: "El bote debe estar limpio en todas sus partes, con bolsa de basura y sin exceso.", valor: 3, orden: 11 },
  { codigo: "EL12", seccionNumero: 2, seccionNombre: "Entrada al Local o Llegada a la Isla", categoria: "Higiene", descripcion: "Se percibe un olor agradable al llegar al establecimiento", criterio: "Se debe percibir un aroma agradable. El aromatizante que se debe utilizar es Manzana-Canela.", valor: 5, orden: 12 },
  { codigo: "EL13", seccionNumero: 2, seccionNombre: "Entrada al Local o Llegada a la Isla", categoria: "Operación", descripcion: "La música está en un volumen y género adecuado", criterio: "Volumen adecuado y de agrado de los clientes. Está permitido: música pop, chill-out, ambiental.", valor: 3, orden: 13 },
  { codigo: "EL14", seccionNumero: 2, seccionNombre: "Entrada al Local o Llegada a la Isla", categoria: "Mantenimiento", descripcion: "El menú se encuentra en buen estado y limpio", criterio: "No debe tener enmendaduras, ni precios encimados y perfectamente limpios y a la vista del cliente.", valor: 3, orden: 14 },
  { codigo: "EL15", seccionNumero: 2, seccionNombre: "Entrada al Local o Llegada a la Isla", categoria: "Mantenimiento", descripcion: "La caja de luz prende y están en buenas condiciones", criterio: "No existen focos fundidos en su interior ni cuarteaduras en la parte del acrílico.", valor: 3, orden: 15 },
  { codigo: "EL16", seccionNumero: 2, seccionNombre: "Entrada al Local o Llegada a la Isla", categoria: "Imagen", descripcion: "Los viniles de puertas y paredes están completos y en buenas condiciones", criterio: "No existen rasgaduras o viniles descolorados.", valor: 1, orden: 16 },
  { codigo: "EL17", seccionNumero: 2, seccionNombre: "Entrada al Local o Llegada a la Isla", categoria: "Imagen", descripcion: "El anuncio luminoso está prendido", criterio: "Se encuentra a todas horas prendido.", valor: 3, orden: 17 },
  { codigo: "EL18", seccionNumero: 2, seccionNombre: "Entrada al Local o Llegada a la Isla", categoria: "Imagen", descripcion: "Los horarios de apertura y cierre están visibles al cliente", criterio: "Los horarios deben encontrarse cerca de la caja o en la entrada y ser respetado.", valor: 1, orden: 18 },
  { codigo: "EL19", seccionNumero: 2, seccionNombre: "Entrada al Local o Llegada a la Isla", categoria: "Imagen", descripcion: "Se cuenta con material de temporada o promocional autorizado por Snowtea", criterio: "Material vigente, en buen estado y colocado según las indicaciones del corporativo. Si no hay campaña activa, se marca N/A.", valor: 3, orden: 19 },
  { codigo: "EL20", seccionNumero: 2, seccionNombre: "Entrada al Local o Llegada a la Isla", categoria: "Higiene", descripcion: "El área de espera del cliente está libre de obstáculos y señalizada", criterio: "No hay cajas, costales ni objetos que dificulten el tránsito del cliente. El área de espera es clara y accesible.", valor: 3, orden: 20 },
  // ─── 3. Producción ────────────────────────────────────────────────────────
  { codigo: "P1", seccionNumero: 3, seccionNombre: "Producción", categoria: "Operación", descripcion: "La elaboración de la tapioca se hace conforme al M.O.", criterio: "El procedimiento se tiene que seguir a detalle y cumplir al 100% con el mismo.", valor: 5, orden: 1 },
  { codigo: "P2", seccionNumero: 3, seccionNombre: "Producción", categoria: "Operación", descripcion: "Se encuentran los accesorios necesarios para hacer tapioca", criterio: "Olla, pala de madera, jarra medidora de agua, reloj cronómetro, estufa, olla de acero, colador para enjuagar.", valor: 1, orden: 2 },
  { codigo: "P3", seccionNumero: 3, seccionNombre: "Producción", categoria: "Operación", descripcion: "Siempre se tiene tapioca suficiente para atender a los clientes antes del cierre", criterio: "De acuerdo con el día y el pronóstico de venta del mismo es la cantidad de tapioca que se elabora.", valor: 5, orden: 3 },
  { codigo: "P4", seccionNumero: 3, seccionNombre: "Producción", categoria: "Operación", descripcion: "El té base se elabora usando el cronómetro y siguiendo el M.O.", criterio: "El pouch de té, al momento de infusionarse, no debe pasar más de 3 min. en contacto con el agua.", valor: 5, orden: 4 },
  { codigo: "P5", seccionNumero: 3, seccionNombre: "Producción", categoria: "Operación", descripcion: "El té base se elabora en el recipiente correcto y con la cantidad correcta de agua", criterio: "Recipiente de acero inoxidable con la cantidad de agua indicada en el M.O.", valor: 5, orden: 5 },
  { codigo: "P6", seccionNumero: 3, seccionNombre: "Producción", categoria: "Operación", descripcion: "Los tés base se encuentran almacenados correctamente", criterio: "En el refrigerador, bien tapados y etiquetados con el nombre y la fecha de elaboración.", valor: 5, orden: 6 },
  { codigo: "P7", seccionNumero: 3, seccionNombre: "Producción", categoria: "Operación", descripcion: "La tapioca se almacena correctamente", criterio: "En el recipiente indicado, con el almíbar correcto y a temperatura ambiente.", valor: 5, orden: 7 },
  { codigo: "P8", seccionNumero: 3, seccionNombre: "Producción", categoria: "Operación", descripcion: "Los sabores están correctamente almacenados", criterio: "En el refrigerador o a temperatura ambiente según corresponda, bien tapados y etiquetados.", valor: 5, orden: 8 },
  { codigo: "P9", seccionNumero: 3, seccionNombre: "Producción", categoria: "Control", descripcion: "Se cuenta con el registro de producción de tapioca actualizado", criterio: "El registro debe estar al día con fecha, hora, cantidad y responsable.", valor: 3, orden: 9 },
  { codigo: "P10", seccionNumero: 3, seccionNombre: "Producción", categoria: "Higiene", descripcion: "El área de producción se encuentra limpia y ordenada", criterio: "Sin residuos de alimentos, utensilios limpios y en su lugar.", valor: 5, orden: 10 },
  { codigo: "P11", seccionNumero: 3, seccionNombre: "Producción", categoria: "Higiene", descripcion: "Los utensilios de producción están limpios y desinfectados", criterio: "Ollas, palas, coladores y demás utensilios limpios y desinfectados.", valor: 5, orden: 11 },
  { codigo: "P12", seccionNumero: 3, seccionNombre: "Producción", categoria: "Operación", descripcion: "Se tiene el inventario de materias primas actualizado", criterio: "El inventario debe estar al día y ser congruente con lo que hay físicamente.", valor: 3, orden: 12 },
  { codigo: "P13", seccionNumero: 3, seccionNombre: "Producción", categoria: "Control", descripcion: "Se verifica la fecha de caducidad de las materias primas antes de usarlas", criterio: "No se utilizan materias primas vencidas. Se retiran del inventario y se reportan al franquiciante de inmediato.", valor: 5, orden: 13 },
  { codigo: "P14", seccionNumero: 3, seccionNombre: "Producción", categoria: "Higiene", descripcion: "Las materias primas se almacenan siguiendo el principio PEPS (Primero en Entrar, Primero en Salir)", criterio: "Los productos más antiguos están al frente y los nuevos al fondo. Aplica para refrigerador y almacén seco.", valor: 5, orden: 14 },
  { codigo: "P15", seccionNumero: 3, seccionNombre: "Producción", categoria: "Operación", descripcion: "Se cuenta con termómetro para verificar la temperatura del té base", criterio: "Termómetro disponible y calibrado. El té base debe enfriarse a menos de 10°C antes de refrigerar.", valor: 3, orden: 15 },
  // ─── 4. Máquina de Hielo ──────────────────────────────────────────────────
  { codigo: "MH1", seccionNumero: 4, seccionNombre: "Máquina de Hielo / Hielera", categoria: "Higiene", descripcion: "La máquina de hielo o hielera está limpia por dentro y por fuera", criterio: "Sin residuos, sin manchas y sin malos olores.", valor: 3, orden: 1 },
  { codigo: "MH2", seccionNumero: 4, seccionNombre: "Máquina de Hielo / Hielera", categoria: "Operación", descripcion: "La máquina de hielo funciona correctamente", criterio: "Produce hielo suficiente para la operación del día.", valor: 5, orden: 2 },
  { codigo: "MH3", seccionNumero: 4, seccionNombre: "Máquina de Hielo / Hielera", categoria: "Higiene", descripcion: "El hielo se maneja con utensilios limpios (pala o cuchara)", criterio: "Nunca se toca el hielo con las manos. Se usa pala o cuchara específica para hielo.", valor: 3, orden: 3 },
  { codigo: "MH4", seccionNumero: 4, seccionNombre: "Máquina de Hielo / Hielera", categoria: "Higiene", descripcion: "La pala o cuchara del hielo está limpia y en su lugar", criterio: "Limpia, desinfectada y guardada en un lugar específico.", valor: 3, orden: 4 },
  { codigo: "MH5", seccionNumero: 4, seccionNombre: "Máquina de Hielo / Hielera", categoria: "Operación", descripcion: "Se cuenta con suficiente hielo para la operación del día", criterio: "Siempre debe haber hielo suficiente para atender a todos los clientes.", valor: 3, orden: 5 },
  { codigo: "MH6", seccionNumero: 4, seccionNombre: "Máquina de Hielo / Hielera", categoria: "Mantenimiento", descripcion: "La máquina de hielo tiene mantenimiento preventivo al corriente", criterio: "Registro de limpieza profunda al menos una vez al mes.", valor: 3, orden: 6 },
  // ─── 5. Equipo ────────────────────────────────────────────────────────────
  { codigo: "EQ1", seccionNumero: 5, seccionNombre: "Equipo", categoria: "Operación", descripcion: "Las licuadoras están limpias y funcionando correctamente", criterio: "Vasos limpios, cuchillas en buen estado y motor funcionando.", valor: 5, orden: 1 },
  { codigo: "EQ2", seccionNumero: 5, seccionNombre: "Equipo", categoria: "Operación", descripcion: "La selladora está limpia y funcionando correctamente", criterio: "La selladora sella correctamente sin dejar burbujas o sellos incompletos.", valor: 5, orden: 2 },
  { codigo: "EQ3", seccionNumero: 5, seccionNombre: "Equipo", categoria: "Operación", descripcion: "El Droper está limpio y funcionando correctamente", criterio: "Limpio, desinfectado y dosificando correctamente.", valor: 5, orden: 3 },
  { codigo: "EQ4", seccionNumero: 5, seccionNombre: "Equipo", categoria: "Operación", descripcion: "El sistema de cómputo (POS) está funcionando correctamente", criterio: "El sistema registra ventas, imprime tickets y funciona sin errores.", valor: 5, orden: 4 },
  { codigo: "EQ5", seccionNumero: 5, seccionNombre: "Equipo", categoria: "Mantenimiento", descripcion: "Todos los equipos tienen mantenimiento preventivo al corriente", criterio: "Registro de mantenimiento preventivo de todos los equipos.", valor: 5, orden: 5 },
  { codigo: "EQ6", seccionNumero: 5, seccionNombre: "Equipo", categoria: "Higiene", descripcion: "Los vasos de las licuadoras se lavan correctamente después de cada uso", criterio: "Con jabón, esponja y agua caliente. Sin residuos de bebidas anteriores. Nunca se enjuagan solo con agua.", valor: 5, orden: 6 },
  { codigo: "EQ7", seccionNumero: 5, seccionNombre: "Equipo", categoria: "Operación", descripcion: "La impresora de tickets tiene papel y funciona correctamente", criterio: "Siempre debe tener papel y estar lista para imprimir.", valor: 3, orden: 7 },
  { codigo: "EQ8", seccionNumero: 5, seccionNombre: "Equipo", categoria: "Mantenimiento", descripcion: "El refrigerador está limpio y a la temperatura correcta", criterio: "Temperatura entre 2°C y 4°C. Limpio por dentro y por fuera.", valor: 5, orden: 8 },
  { codigo: "EQ9", seccionNumero: 5, seccionNombre: "Equipo", categoria: "Operación", descripcion: "El refrigerador está organizado y con los productos bien identificados", criterio: "Productos etiquetados con nombre y fecha. Organizados por tipo.", valor: 3, orden: 9 },
  { codigo: "EQ10", seccionNumero: 5, seccionNombre: "Equipo", categoria: "Mantenimiento", descripcion: "El Redwash está limpio y funcionando correctamente", criterio: "Limpio, con el producto correcto y funcionando.", valor: 5, orden: 10 },
  { codigo: "EQ11", seccionNumero: 5, seccionNombre: "Equipo", categoria: "Operación", descripcion: "La báscula está calibrada y funcionando correctamente", criterio: "Calibrada y con batería.", valor: 3, orden: 11 },
  { codigo: "EQ12", seccionNumero: 5, seccionNombre: "Equipo", categoria: "Higiene", descripcion: "El área de equipos está limpia y ordenada", criterio: "Sin residuos, equipos en su lugar y superficies limpias.", valor: 5, orden: 12 },
  { codigo: "EQ13", seccionNumero: 5, seccionNombre: "Equipo", categoria: "Mantenimiento", descripcion: "Los cables y conexiones eléctricas están en buen estado", criterio: "Sin cables pelados, bien organizados y sin riesgo eléctrico.", valor: 3, orden: 13 },
  { codigo: "EQ14", seccionNumero: 5, seccionNombre: "Equipo", categoria: "Operación", descripcion: "Se cuenta con los accesorios necesarios para la operación (popotes, servilletas, vasos)", criterio: "Siempre debe haber suficiente inventario de accesorios para la operación del día.", valor: 5, orden: 14 },
  { codigo: "EQ16", seccionNumero: 5, seccionNombre: "Equipo", categoria: "Mantenimiento", descripcion: "La selladora tiene el tiempo y temperatura de sellado calibrados correctamente", criterio: "Configuración según especificaciones del M.O. Se verifica con prueba de sello al inicio del turno. Un sello deficiente puede causar derrames y mala presentación.", valor: 5, orden: 15 },
  { codigo: "EQ17", seccionNumero: 5, seccionNombre: "Equipo", categoria: "Higiene", descripcion: "El Droper se limpia y desinfecta al inicio y al final de cada turno", criterio: "Registro de limpieza del Droper en la BUOS. Sin residuos de bebidas anteriores en la boquilla ni en el cuerpo del equipo.", valor: 5, orden: 16 },
  // ─── 6. Operación del Negocio ─────────────────────────────────────────────
  { codigo: "ON2", seccionNumero: 6, seccionNombre: "Operación del Negocio", categoria: "Control", descripcion: "El corte de caja se realiza correctamente al final del turno", criterio: "El corte de caja coincide con el sistema POS.", valor: 5, orden: 1 },
  { codigo: "ON3", seccionNumero: 6, seccionNombre: "Operación del Negocio", categoria: "Operación", descripcion: "El personal conoce el menú completo y los ingredientes de cada bebida", criterio: "Puede describir cualquier bebida del menú sin dudar.", valor: 5, orden: 2 },
  { codigo: "ON4", seccionNumero: 6, seccionNombre: "Operación del Negocio", categoria: "Operación", descripcion: "Las bebidas se elaboran siguiendo las recetas del M.O.", criterio: "Cantidades exactas de ingredientes según el M.O.", valor: 5, orden: 3 },
  { codigo: "ON5", seccionNumero: 6, seccionNombre: "Operación del Negocio", categoria: "Operación", descripcion: "Los precios del menú están actualizados y son correctos", criterio: "Los precios en el menú coinciden con los del sistema POS.", valor: 3, orden: 4 },
  { codigo: "ON6", seccionNumero: 6, seccionNombre: "Operación del Negocio", categoria: "Control", descripcion: "Se lleva el control de inventario diariamente", criterio: "Registro diario de entradas y salidas de inventario.", valor: 5, orden: 5 },
  { codigo: "ON7", seccionNumero: 6, seccionNombre: "Operación del Negocio", categoria: "Operación", descripcion: "El personal porta el uniforme completo y limpio", criterio: "Uniforme completo según estándar Snowtea: playera, delantal, gorra. Sin prendas adicionales no autorizadas.", valor: 5, orden: 6 },
  { codigo: "ON8", seccionNumero: 6, seccionNombre: "Operación del Negocio", categoria: "Higiene", descripcion: "El personal mantiene higiene personal adecuada", criterio: "Manos limpias, uñas cortas y sin esmalte, cabello recogido.", valor: 5, orden: 7 },
  { codigo: "ON9", seccionNumero: 6, seccionNombre: "Operación del Negocio", categoria: "Operación", descripcion: "Se respetan los tiempos de elaboración de bebidas", criterio: "Las bebidas se elaboran en el tiempo indicado en el M.O. El cliente no debe esperar más de 3 minutos para un pedido estándar.", valor: 5, orden: 8 },
  { codigo: "ON10", seccionNumero: 6, seccionNombre: "Operación del Negocio", categoria: "Control", descripcion: "Se lleva el registro de temperaturas del refrigerador", criterio: "Registro diario de temperatura del refrigerador.", valor: 3, orden: 9 },
  { codigo: "ON11", seccionNumero: 6, seccionNombre: "Operación del Negocio", categoria: "Operación", descripcion: "El área de trabajo está organizada para una operación eficiente", criterio: "Todo en su lugar y accesible para una operación rápida. Incluye accesorios, utensilios y materias primas.", valor: 5, orden: 10 },
  { codigo: "ON12", seccionNumero: 6, seccionNombre: "Operación del Negocio", categoria: "Higiene", descripcion: "Se utilizan guantes para el manejo de alimentos cuando es necesario", criterio: "Guantes limpios para manejo de tapioca y otros ingredientes.", valor: 3, orden: 11 },
  { codigo: "ON13", seccionNumero: 6, seccionNombre: "Operación del Negocio", categoria: "Operación", descripcion: "Las bebidas se presentan correctamente (vaso, tapa, popote)", criterio: "Presentación correcta según estándar Snowtea.", valor: 3, orden: 12 },
  { codigo: "ON14", seccionNumero: 6, seccionNombre: "Operación del Negocio", categoria: "Control", descripcion: "Se cuenta con el manual de operaciones actualizado y accesible", criterio: "El M.O. debe estar en el local y accesible para el personal.", valor: 5, orden: 13 },
  { codigo: "ON15", seccionNumero: 6, seccionNombre: "Operación del Negocio", categoria: "Operación", descripcion: "El personal conoce los procedimientos de emergencia", criterio: "Sabe qué hacer en caso de emergencia (incendio, accidente, etc.).", valor: 3, orden: 14 },
  { codigo: "ON16", seccionNumero: 6, seccionNombre: "Operación del Negocio", categoria: "Operación", descripcion: "Se realizan pedidos de materias primas con anticipación suficiente", criterio: "Nunca se queda sin materias primas por falta de planeación.", valor: 5, orden: 15 },
  { codigo: "ON17", seccionNumero: 6, seccionNombre: "Operación del Negocio", categoria: "Control", descripcion: "Se reportan incidencias y problemas al franquiciante", criterio: "Comunicación oportuna de cualquier problema o incidencia.", valor: 3, orden: 16 },
  { codigo: "ON18", seccionNumero: 6, seccionNombre: "Operación del Negocio", categoria: "Control", descripcion: "Se realiza conteo físico de inventario al inicio y al cierre del turno", criterio: "Conteo registrado en la BUOS con firma del responsable. El conteo debe coincidir con el sistema POS.", valor: 5, orden: 17 },
  { codigo: "ON19", seccionNumero: 6, seccionNombre: "Operación del Negocio", categoria: "Hospitalidad", descripcion: "El personal ofrece activamente el programa de lealtad o promociones vigentes", criterio: "Menciona el programa de lealtad o la promoción del mes a cada cliente. Si no hay programa activo, se marca N/A.", valor: 3, orden: 18 },
  { codigo: "ON20", seccionNumero: 6, seccionNombre: "Operación del Negocio", categoria: "Operación", descripcion: "El personal conoce y puede explicar los alérgenos de las bebidas del menú", criterio: "Puede indicar qué bebidas contienen lácteos, gluten o frutos secos. Información disponible para el cliente que lo solicite.", valor: 3, orden: 19 },
  // ─── 7. Instalaciones y Mobiliario ───────────────────────────────────────
  { codigo: "IM1", seccionNumero: 7, seccionNombre: "Instalaciones y Mobiliario", categoria: "Mantenimiento", descripcion: "Las paredes y techo están en buen estado (sin grietas, manchas o humedad)", criterio: "Visualmente en buen estado, pintura en buen estado y sin humedad.", valor: 3, orden: 1 },
  { codigo: "IM2", seccionNumero: 7, seccionNombre: "Instalaciones y Mobiliario", categoria: "Mantenimiento", descripcion: "El piso interior está en buen estado, limpio y sin chicles pegados", criterio: "Sin grietas, manchas o baldosas rotas. Limpio, trapeado y sin chicles pegados en toda el área interior del local.", valor: 3, orden: 2 },
  { codigo: "IM3", seccionNumero: 7, seccionNombre: "Instalaciones y Mobiliario", categoria: "Higiene", descripcion: "El baño (si aplica) está limpio y bien equipado", criterio: "Limpio, con jabón, papel higiénico y toallas o secador.", valor: 5, orden: 3 },
  { codigo: "IM4", seccionNumero: 7, seccionNombre: "Instalaciones y Mobiliario", categoria: "Mantenimiento", descripcion: "El mobiliario (mesas, sillas, barra) está en buen estado", criterio: "Sin roturas, manchas permanentes o deterioro visible.", valor: 3, orden: 4 },
  { codigo: "IM5", seccionNumero: 7, seccionNombre: "Instalaciones y Mobiliario", categoria: "Imagen", descripcion: "La decoración y señalización interior está completa y en buen estado", criterio: "Todos los elementos decorativos y señalización según estándar Snowtea.", valor: 3, orden: 5 },
  { codigo: "IM6", seccionNumero: 7, seccionNombre: "Instalaciones y Mobiliario", categoria: "Mantenimiento", descripcion: "La iluminación interior y exterior es adecuada y todos los focos funcionan", criterio: "Iluminación suficiente en interior y exterior. Todos los focos en funcionamiento, sin focos fundidos en techo, barra ni exteriores.", valor: 5, orden: 6 },
  { codigo: "IM7", seccionNumero: 7, seccionNombre: "Instalaciones y Mobiliario", categoria: "Higiene", descripcion: "Las superficies de trabajo están limpias y desinfectadas", criterio: "Barra de atención, área de producción y todas las superficies de trabajo.", valor: 5, orden: 7 },
  { codigo: "IM8", seccionNumero: 7, seccionNombre: "Instalaciones y Mobiliario", categoria: "Mantenimiento", descripcion: "No existen viniles sobrepuestos o en mal estado en el interior", criterio: "Todos los viniles en buen estado y sin superposiciones.", valor: 2, orden: 8 },
  { codigo: "IM9", seccionNumero: 7, seccionNombre: "Instalaciones y Mobiliario", categoria: "Mantenimiento", descripcion: "Las salidas de agua cuentan con filtro de purificación y funciona correctamente", criterio: "Filtro instalado y en funcionamiento.", valor: 3, orden: 9 },
  { codigo: "IM10", seccionNumero: 7, seccionNombre: "Instalaciones y Mobiliario", categoria: "Operación", descripcion: "Se cuenta con un 'no break' para el equipo de cómputo", criterio: "No break instalado y funcionando.", valor: 3, orden: 10 },
  { codigo: "IM12", seccionNumero: 7, seccionNombre: "Instalaciones y Mobiliario", categoria: "Imagen", descripcion: "Se encuentran los posters de la medida y los autorizados por Snowtea", criterio: "Solo posters autorizados por Snowtea en las medidas correctas.", valor: 3, orden: 11 },
  // ─── 8. Higiene Operativa ─────────────────────────────────────────────────
  { codigo: "HO1", seccionNumero: 8, seccionNombre: "Higiene Operativa", categoria: "Operación", descripcion: "Se da seguimiento a los procedimientos de limpieza del M.O.", criterio: "Los procedimientos de limpieza del M.O. se siguen al 100%.", valor: 5, orden: 1 },
  { codigo: "HO2", seccionNumero: 8, seccionNombre: "Higiene Operativa", categoria: "Higiene", descripcion: "Se cuenta con los productos de limpieza necesarios", criterio: "Jabón, cloro, desinfectante, trapos por área, escoba, trapeador.", valor: 3, orden: 2 },
  { codigo: "HO3", seccionNumero: 8, seccionNombre: "Higiene Operativa", categoria: "Higiene", descripcion: "Los trapos están identificados por área y se usan correctamente", criterio: "Trapos de diferentes colores por área (producción, barra, pisos).", valor: 3, orden: 3 },
  { codigo: "HO4", seccionNumero: 8, seccionNombre: "Higiene Operativa", categoria: "Higiene", descripcion: "La boquilla de la mamila del chamoy está limpia", criterio: "Limpia y sin residuos de chamoy.", valor: 5, orden: 4 },
  { codigo: "HO5", seccionNumero: 8, seccionNombre: "Higiene Operativa", categoria: "Higiene", descripcion: "No existen residuos de chicles pegados en el suelo y barras de servicio", criterio: "Piso y barras sin chicles pegados. Se revisa tanto el área interior como la barra de atención al cliente.", valor: 5, orden: 5 },
  { codigo: "HO6", seccionNumero: 8, seccionNombre: "Higiene Operativa", categoria: "Higiene", descripcion: "Existe solución de alcohol en gel para desinfección de manos en producción", criterio: "Alcohol en gel disponible y accesible en el área de producción.", valor: 5, orden: 6 },
  { codigo: "HO8", seccionNumero: 8, seccionNombre: "Higiene Operativa", categoria: "Higiene", descripcion: "Se realiza limpieza profunda del área de producción al menos una vez por semana", criterio: "Registro en la BUOS con fecha y responsable. Incluye limpieza de paredes, equipos, pisos y techos del área de producción.", valor: 5, orden: 7 },
  { codigo: "HO9", seccionNumero: 8, seccionNombre: "Higiene Operativa", categoria: "Higiene", descripcion: "Los productos de limpieza están almacenados separados de los alimentos", criterio: "Nunca en el mismo espacio físico que materias primas o bebidas. Deben estar en un área designada y etiquetada.", valor: 5, orden: 8 },
  { codigo: "HO10", seccionNumero: 8, seccionNombre: "Higiene Operativa", categoria: "Control", descripcion: "Se cuenta con un programa de limpieza semanal visible y firmado", criterio: "Programa impreso, firmado por el encargado y actualizado con las actividades de la semana en curso.", valor: 3, orden: 9 },
  // ─── 9. Ciclo de Servicio ─────────────────────────────────────────────────
  { codigo: "SC1", seccionNumero: 9, seccionNombre: "Ciclo de Servicio", categoria: "Hospitalidad", descripcion: "El personal está sonriente y en buena actitud con el cliente todo el tiempo", criterio: "Siempre sonrientes y con actitud de servicio.", valor: 5, orden: 1 },
  { codigo: "SC2", seccionNumero: 9, seccionNombre: "Ciclo de Servicio", categoria: "Hospitalidad", descripcion: "En su saludo inicial menciona la palabra Snowtea", criterio: "El saludo debe incluir el nombre de la marca.", valor: 5, orden: 2 },
  { codigo: "SC3", seccionNumero: 9, seccionNombre: "Ciclo de Servicio", categoria: "Hospitalidad", descripcion: "Hace recomendaciones de algún sabor", criterio: "Siempre ofrece una recomendación de sabor al cliente.", valor: 5, orden: 3 },
  { codigo: "SC4", seccionNumero: 9, seccionNombre: "Ciclo de Servicio", categoria: "Operación", descripcion: "Informa al cliente el tipo de bebida que desea (base yogurt, chamoy, original)", criterio: "Confirma el tipo de base con el cliente.", valor: 5, orden: 4 },
  { codigo: "SC5", seccionNumero: 9, seccionNombre: "Ciclo de Servicio", categoria: "Hospitalidad", descripcion: "Los M.E. explican qué es la tapioca a los invitados de manera entusiasta y amable", criterio: "Explicación clara y entusiasta de la tapioca.", valor: 5, orden: 5 },
  { codigo: "SC6", seccionNumero: 9, seccionNombre: "Ciclo de Servicio", categoria: "Hospitalidad", descripcion: "Ofrece degustación al inicio de la atención y al momento de entregar la bebida", criterio: "Al inicio, ofrece degustación del sabor recomendado. Al entregar la bebida, ofrece degustación de un sabor diferente al pedido. Maneja la degustación con palito limpio y porción correcta.", valor: 5, orden: 6 },
  { codigo: "SC9", seccionNumero: 9, seccionNombre: "Ciclo de Servicio", categoria: "Hospitalidad", descripcion: "Invita al cliente a regresar pronto al Snowtea", criterio: "Despedida cálida invitando al cliente a regresar.", valor: 5, orden: 7 },
  { codigo: "SC10", seccionNumero: 9, seccionNombre: "Ciclo de Servicio", categoria: "Hospitalidad", descripcion: "El personal pregunta si es la primera visita del cliente y personaliza la experiencia", criterio: "Si es primera visita, explica el concepto completo. Si es cliente frecuente, lo reconoce y lo llama por su nombre si es posible.", valor: 5, orden: 8 },
  { codigo: "SC11", seccionNumero: 9, seccionNombre: "Ciclo de Servicio", categoria: "Hospitalidad", descripcion: "Ante una queja o error en el pedido, el personal actúa con el protocolo correcto", criterio: "Pide disculpas de inmediato, corrige el pedido sin costo adicional y reporta el incidente al encargado. No discute con el cliente.", valor: 5, orden: 9 },
  // ─── 10. Documentación y Legales ─────────────────────────────────────────
  { codigo: "D1", seccionNumero: 10, seccionNombre: "Documentación y Legales", categoria: "Control", descripcion: "Cuenta con licencia de funcionamiento al corriente", criterio: "Licencia vigente y visible.", valor: 5, orden: 1 },
  { codigo: "D2", seccionNumero: 10, seccionNombre: "Documentación y Legales", categoria: "Control", descripcion: "Cuenta con bitácora de fumigación o servicio actualizado de control de plagas", criterio: "Bitácora al día con el último servicio.", valor: 5, orden: 2 },
  { codigo: "D3", seccionNumero: 10, seccionNombre: "Documentación y Legales", categoria: "Control", descripcion: "Cuenta con el 'Visto Bueno' de protección civil", criterio: "Documento vigente y visible.", valor: 5, orden: 3 },
  { codigo: "D4", seccionNumero: 10, seccionNombre: "Documentación y Legales", categoria: "Control", descripcion: "Cuenta con extintor de CO2 (no de polvo)", criterio: "Extintor de CO2 vigente y en su lugar.", valor: 5, orden: 4 },
  { codigo: "D5", seccionNumero: 10, seccionNombre: "Documentación y Legales", categoria: "Control", descripcion: "Cuenta con Botiquín de Primeros Auxilios", criterio: "Botiquín completo y accesible.", valor: 5, orden: 5 },
  { codigo: "D6", seccionNumero: 10, seccionNombre: "Documentación y Legales", categoria: "Control", descripcion: "Cuenta con las señalizaciones solicitadas por protección civil", criterio: "Señalización completa según protección civil.", valor: 5, orden: 6 },
  { codigo: "D7", seccionNumero: 10, seccionNombre: "Documentación y Legales", categoria: "Control", descripcion: "Se tiene al corriente la 'BUOS' Bitácora Única de Operaciones Snowtea", criterio: "BUOS al día con todas las operaciones registradas.", valor: 5, orden: 7 },
  { codigo: "D8", seccionNumero: 10, seccionNombre: "Documentación y Legales", categoria: "Control", descripcion: "La 'BUOS' se encuentra almacenada por lo menos con 6 meses de antigüedad", criterio: "Historial de al menos 6 meses en la BUOS.", valor: 3, orden: 8 },
  { codigo: "D9", seccionNumero: 10, seccionNombre: "Documentación y Legales", categoria: "Control", descripcion: "Se tiene al corriente los formatos de limpieza", criterio: "Formatos de limpieza al día y firmados.", valor: 5, orden: 9 },
  { codigo: "D10", seccionNumero: 10, seccionNombre: "Documentación y Legales", categoria: "Control", descripcion: "Se cuenta con el contrato de franquicia vigente y accesible en el local", criterio: "Copia del contrato vigente en el local, disponible para revisión.", valor: 3, orden: 10 },
];

// Puntos a desactivar (eliminados por duplicados o fusionados)
const DESACTIVAR = ["ON1", "EQ15", "HO7", "IM11", "SC7", "SC8"];

async function seed() {
  const conn = await mysql.createConnection(process.env.DATABASE_URL);
  console.log(`Actualizando ${PUNTOS.length} puntos de evaluación en la base de datos...`);

  for (const p of PUNTOS) {
    await conn.execute(
      `INSERT INTO puntos_evaluacion (codigo, seccionNumero, seccionNombre, categoria, descripcion, criterio, valor, orden, activo)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, true)
       ON DUPLICATE KEY UPDATE
         seccionNumero=VALUES(seccionNumero), seccionNombre=VALUES(seccionNombre),
         categoria=VALUES(categoria), descripcion=VALUES(descripcion),
         criterio=VALUES(criterio), valor=VALUES(valor), orden=VALUES(orden), activo=true`,
      [p.codigo, p.seccionNumero, p.seccionNombre, p.categoria, p.descripcion, p.criterio, p.valor, p.orden]
    );
  }

  for (const codigo of DESACTIVAR) {
    await conn.execute(`UPDATE puntos_evaluacion SET activo=false WHERE codigo=?`, [codigo]);
  }

  await conn.end();
  console.log(`✓ Seed completado: ${PUNTOS.length} puntos activos, ${DESACTIVAR.length} desactivados`);
}

seed().catch(e => { console.error(e); process.exit(1); });
